# Generated by Django 2.0 on 2017-12-07 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaReservacion', models.DateField()),
                ('formaPago', models.CharField(choices=[('E', 'Efectivo'), ('T', 'Tarjeta')], default='T', max_length=1)),
                ('numPersonas', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habitacion.Habitacion')),
            ],
        ),
    ]
